### ISSUE TITLE
Dependency Updater should look for Carthage dependencies

### ISSUE THREAD

**Issue by SlaunchaMan** [detroit-labs/fastlane-template#16]
The Dependency Updater should look for a `Cartfile` and, if present, run `carthage update`. We should probably also refactor to only run `pod update` if there’s a `Podfile`, and prepend `bundle exec` to it (and run `bundle update`) if there’s a `Gemfile`.

**Comment by jshier** [comment]
Probably want to make the `bundle exec` dynamic (I think Fastlane can detect it, maybe use that?).
